# Generated by Django 3.1.5 on 2021-02-23 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20210223_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('number', models.CharField(max_length=12)),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
                ('Interest', models.CharField(max_length=25)),
                ('Assignedto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadsassigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
