# Generated by Django 3.1.5 on 2021-02-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20210224_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='stage',
            new_name='status',
        ),
    ]
