# Generated by Django 3.1.5 on 2021-02-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20210228_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
