# Generated by Django 3.1.5 on 2021-02-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_lead_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitytype', models.CharField(max_length=25)),
                ('text', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('oflead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadactivity', to='business.lead')),
            ],
        ),
    ]
