# Generated by Django 3.1.5 on 2021-03-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20210302_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='stage',
        ),
    ]
